spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true


file:
  dir: /second/images


springdoc:
  # 응답 데이터 형태
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      # API문서 그룹화 여부
      enabled: true
  swagger-ui:
    # 정렬 기준 (알파벳 기준)
    operations-sorter: alpha
    tags-sorter: alpha
    # swagger 접근 기본 경로
    path: /swagger
    # 기본 경로 설정 비활성화 여부
    disable-swagger-default-url: true
    # 문서 확장기능 사용 여부
    doc-expansion: none
  paths-to-match:
    # '-'은 일반 properties 파일의 콤마 같은 느낌 어레이를 표현
    - /api/**
    # 문서로 만들 API 요청 경로 목록 (요청 경로가 /api/로 시작하면 모두 문서화)
