server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monthly_coffee_db_dev
    username: root
    password: 1234
  
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
